"""Initial Database

Revision ID: b0c91fd0b180
Revises: 
Create Date: 2026-01-21 13:50:53.872721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c91fd0b180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('min_cgpa', sa.Float(), nullable=False),
    sa.CheckConstraint('min_cgpa >= 0.0 AND min_cgpa <= 10.0', name='drive_eligibility_cgpa_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('code', sa.String(length=7), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('duration_years > 0', name='programme_duration_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Enum('admin', 'student', 'company', name='usertype'), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_type_active', ['user_type', 'is_active'], unique=False)

    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prog_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['prog_id'], ['programme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('industry', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.CheckConstraint('length(contact_number) >= 7 AND length(contact_number) <= 15', name='company_contact_number_length'),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('idx_company_approval', ['is_approved'], unique=False)

    op.create_table('drive_eligibility_branches',
    sa.Column('eligibility_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['eligibility_id'], ['drive_eligibility.id'], ),
    sa.PrimaryKeyConstraint('eligibility_id', 'branch_id')
    )
    op.create_table('placement_drive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='driveapprovalstatus'), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'active', 'closed', 'cancelled', name='drivestatus'), nullable=False),
    sa.Column('title', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('work_mode', sa.Enum('onsite', 'remote', 'hybrid', name='workmode'), nullable=False),
    sa.Column('job_location', sa.String(length=255), nullable=False),
    sa.Column('eligibility', sa.Integer(), nullable=False),
    sa.Column('number_of_vacancies', sa.Integer(), nullable=False),
    sa.Column('opening', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.CheckConstraint('deadline > opening', name='placement_drive_deadline_after_opening'),
    sa.CheckConstraint('length(job_location) > 0', name='placement_drive_job_location_not_empty'),
    sa.CheckConstraint('number_of_vacancies > 0', name='placement_drive_positive_vacancies'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['eligibility'], ['drive_eligibility.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'title', name='unique_company_drive_title')
    )
    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.create_index('idx_placement_drive_company', ['company_id'], unique=False)
        batch_op.create_index('idx_placement_drive_status', ['approval_status', 'status', 'opening'], unique=False)
        batch_op.create_index('idx_placement_work_mode', ['work_mode'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('m', 'f', 'o', name='gender'), nullable=False),
    sa.Column('roll', sa.String(length=10), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('prog_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('admission_year >= 2000', name='student_admission_year_valid'),
    sa.CheckConstraint('current_level >= 1', name='student_current_level_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prog_id'], ['programme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('idx_student_branch', ['branch_id'], unique=False)
        batch_op.create_index('idx_student_programme', ['prog_id'], unique=False)
        batch_op.create_index('idx_student_year_level', ['current_level', 'admission_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_roll'), ['roll'], unique=True)

    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('applied_on', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('applied', 'short_listed', 'selected', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('status_updated_on', sa.DateTime(), nullable=False),
    sa.Column('resume_url', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drive.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'drive_id', name='unique_student_drive_application')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index('idx_application_applied_on', ['student_id', 'applied_on'], unique=False)
        batch_op.create_index('idx_application_drive', ['drive_id'], unique=False)
        batch_op.create_index('idx_application_status', ['status'], unique=False)
        batch_op.create_index('idx_application_student', ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index('idx_application_student')
        batch_op.drop_index('idx_application_status')
        batch_op.drop_index('idx_application_drive')
        batch_op.drop_index('idx_application_applied_on')

    op.drop_table('application')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_roll'))
        batch_op.drop_index('idx_student_year_level')
        batch_op.drop_index('idx_student_programme')
        batch_op.drop_index('idx_student_branch')

    op.drop_table('student')
    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.drop_index('idx_placement_work_mode')
        batch_op.drop_index('idx_placement_drive_status')
        batch_op.drop_index('idx_placement_drive_company')

    op.drop_table('placement_drive')
    op.drop_table('drive_eligibility_branches')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('idx_company_approval')

    op.drop_table('company')
    op.drop_table('branch')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_type_active')

    op.drop_table('user')
    op.drop_table('programme')
    op.drop_table('drive_eligibility')
    # ### end Alembic commands ###
